version: 2

sources:
  - name: WindForecast
    database: proyectofinal-404315
    tables:
      - name: WindSpeed_EXT
        description: Velocidad del Viento años 2021, 2022, 2023
      - name: WindsDirect_EXT
        description: Dirección del Viento años 2021, 2022, 2023