WindsForecast:
  outputs:
    dev:
      dataset: WindForecast
      job_execution_timeout_seconds: 1200
      job_retries: 1
      keyfile: /workspaces/WindForecast/dbt-template/key.json
      location: US
      method: service-account
      priority: interactive
      project: clase09082023
      threads: 1
      type: bigquery
  target: dev